### ISSUE TITLE
Qwen3-8B RL Training with Eagle3 Spec Decoding OOM error

### ISSUE THREAD

**Issue by gxlvera** [THUDM/slime#1022]
### Bug Description
When conducting RL training with Eagle3 speculative decoding on Qwen3-8B on 4\*H200 (and even 8\*H200), GPU OOM always occur after only 3~4 rollout steps.
According to the log, GPU memory usage keeps rising after each rollout step even though `flush_cache` and `release_memory_occupation` are called on the SGLang side. (An inspection of the full log indicates that, after each rollout step, the memory usage increases by about 15GB). It might be the cases that `resume_memory_occupation` allocates too much memory, or `release_memory_occupation` release too little, causing a memory leak across rollouts. 
An excerpt of the OOM error is shown below:
```text
[36m(MegatronTrainRayActor pid=982439)[0m [2025-12-03 06:17:51] timer.py:24 - Timer sleep start
[36m(MegatronTrainRayActor pid=982439)[0m [2025-12-03 06:17:52] memory_utils.py:41 - [Rank 0] Memory-Usage before offload model: {'gpu': '0', 'total_GB': 139.8, 'free_GB': 51.45, 'used_GB': 88.35, 'allocated_GB': 80.63, 'reserved_GB': 81.22}
[36m(MegatronTrainRayActor pid=982439)[0m [2025-12-03 06:17:54] memory_utils.py:41 - [Rank 0] Memory-Usage after offload model: {'gpu': '0', 'total_GB': 139.8, 'free_GB': 88.47, 'used_GB': 51.34, 'allocated_GB': 80.63, 'reserved_GB': 81.22}
[36m(MegatronTrainRayActor pid=982439)[0m [2025-12-03 06:17:54] timer.py:32 - Timer sleep end (elapsed: 2.4s)

[36m(SGLangEngine pid=980268)[0m [2025-12-03 06:17:55] INFO: 172.17.0.3:53854 - "POST /resume_memory_occupation HTTP/1.1" 200 OK
[36m(SGLangEngine pid=980266)[0m [2025-12-03 06:17:17] INFO: 172.17.0.3:40948 - "GET /health HTTP/1.1" 200 OK [32m[repeated 3x across cluster][0m
[36m(SGLangEngine pid=980269)[0m [2025-12-03 06:17:55] Cache flushed successfully!
[36m(SGLangEngine pid=980269)[0m [2025-12-03 06:17:55] INFO: 172.17.0.3:48178 - "GET /flush_cache HTTP/1.1" 200 OK

[36m(MegatronTrainRayActor pid=982439)[0m [2025-12-03 06:17:55] timer.py:24 - Timer update_weights start
[36m(MegatronTrainRayActor pid=982439)[0m [2025-12-03 06:17:55] reloadable_process_group.py:145 - Reloading 7 process groups in pid 982439
[36m(MegatronTrainRayActor pid=982439)[0m [2025-12-03 06:17:55] memory_utils.py:41 - [Rank 0] Memory-Usage before update_weights: {'gpu': '0', 'total_GB': 139.8, 'free_GB': 70.92, 'used_GB': 68.88, 'allocated_GB': 80.63, 'reserved_GB': 81.22}

[36m(MegatronTrainRayActor pid=982439)[0m Update weights:   0%|          | 0/38 [00:00<?, ?it/s]
[36m(SGLangEngine pid=980269)[0m [2025-12-03 06:17:55] INFO: 172.17.0.3:48180 - "POST /update_weights_from_tensor HTTP/1.1" 200 OK
[36m(SGLangEngine pid=980269)[0m [2025-12-03 06:17:55] INFO: 172.17.0.3:48184 - "POST /update_weights_from_tensor HTTP/1.1" 200 OK

[36m(MegatronTrainRayActor pid=982439)[0m Update weights:   3%|▎         | 1/38 [00:00<00:10,  3.58it/s]
[36m(MegatronTrainRayActor pid=982439)[0m Update weights:  21%|██        | 8/38 [00:00<00:01, 25.95it/s]
[36m(MegatronTrainRayActor pid=982439)[0m Update weights:  39%|███▉      | 15/38 [00:00<00:00, 39.36it/s]
[36m(MegatronTrainRayActor pid=982439)[0m Update weights:  58%|█████▊    | 22/38 [00:00<00:00, 48.35it/s]
[36m(MegatronTrainRayActor pid=982439)[0m Update weights:  79%|███████▉  | 30/38 [00:00<00:00, 56.12it/s]
[36m(MegatronTrainRayActor pid=982439)[0m Update weights:  97%|█████████▋| 37/38 [00:00<00:00, 52.79it/s]
[36m(MegatronTrainRayActor pid=982439)[0m Update weights: 100%|██████████| 38/38 [00:00<00:00, 41.60it/s]

[36m(MegatronTrainRayActor pid=982439)[0m [2025-12-03 06:17:56] memory_utils.py:41 - [Rank 0] Memory-Usage after update_weights:
{'gpu': '0', 'total_GB': 139.8, 'free_GB': 49.36, 'used_GB': 90.44, 'allocated_GB': 95.89, 'reserved_GB': 101.91}

[36m(SGLangEngine pid=980267)[0m [torch_memory_saver.cpp] cuMemCreate CUDA_ERROR_OUT_OF_MEMORY (may not be an issue e.g. torch allocator will free cache and retry)
[36m(SGLangEngine pid=980267)[0m [torch_memory_saver.cpp] cudaError error: 2 (out of memory)  file=csrc/core.cpp func=resume line=182

[36m(MegatronTrainRayActor pid=982439)[0m [2025-12-03 06:17:56] timer.py:32 - Timer update_weights end (elapsed: 1.2s)

[36m(SGLangEngine pid=980266)[0m [2025-12-03 06:17:56] INFO: 172.17.0.3:54568 - "POST /resume_memory_occupation HTTP/1.1" 200 OK [32m[repeated 10x across cluster][0m
[36m(SGLangEngine pid=980269)[0m [2025-12-03 06:18:17] INFO: 172.17.0.3:38206 - "GET /health HTTP/1.1" 200 OK
[36m(SGLangEngine pid=980266)[0m [2025-12-03 06:17:55] INFO: 172.17.0.3:54140 - "GET /flush_cache HTTP/1.1" 200 OK [32m[repeated 3x across cluster][0m
[36m(SGLangEngine pid=980266)[0m [2025-12-03 06:17:56] INFO: 172.17.0.3:54546 - "POST /update_weights_from_tensor HTTP/1.1" 200 OK [32m[repeated 150x across cluster][0m
[36m(SGLangEngine pid=980267)[0m [2025-12-03 06:18:17] INFO: 172.17.0.3:33086 - "GET /health HTTP/1.1" 200 OK
[36m(SGLangEngine pid=980269)[0m [2025-12-03 06:19:17] INFO: 172.17.0.3:41328 - "GET /health HTTP/1.1" 200 OK [32m[repeated 3x across cluster][0m
[36m(SGLangEngine pid=980269)[0m [2025-12-03 06:20:17] INFO: 172.17.0.3:38886 - "GET /health HTTP/1.1" 200 OK [32m[repeated 4x across cluster][0m
```
full error log:
[run-qwen3-8b-rl-eagle3-OOM-issue.log](https://github.com/user-attachments/files/23918013/run-qwen3-8b-rl-eagle3-OOM-issue.log)

### Environment
1. NVIDIA-SMI 575.57.08 Driver Version: 575.57.08 CUDA Version: 12.9, H200
2. image: slimerl/slime:latest
### Steps for reproducing the bug

1. download models and dataset
```text
hf download Qwen/Qwen3-8B --local-dir /root/Qwen3-8B
hf download Zjcxy-SmartAI/Eagle3-Qwen3-8B-zh --local-dir /root/Eagle3-Qwen3-8B-zh
hf download download --repo-type dataset zyzshishui0627/gsm8k --local-dir /root/gsm8k
```
2. convert model to torch_dist
```text
cd /root/slime
source scripts/models/qwen3-8B.sh
PYTHONPATH=/root/Megatron-LM python tools/convert_hf_to_torch_dist.py \
    ${MODEL_ARGS[@]} \
    --hf-checkpoint /root/Qwen3-8B \
    --save /root/Qwen3-8B_torch_dist
```
3. run this script
```text
cd /root/slime
bash ./scripts/run-qwen3-8b-rl-eagle3.sh
```
[run-qwen3-8b-rl-eagle3.sh](https://github.com/user-attachments/files/23918218/run-qwen3-8b-rl-eagle3.sh)

### Expected behavior
1. GPU memory usage should remain almost constant across rollout steps (memory usage before rollout starts and after rollout ends should be almost identical, rather than increasing).
2. RL training with Slime + SGLang + Eagle3 on Qwen3-8B should run without CUDA OOM on 4×H200 or 8×H200.

**Comment by guapisolo** [comment]
I will take this issue. Thanks!

**Comment by bingyang-lei** [comment]
hi, when i try to reproducing your bug, i meet another error:

```
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111) 
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111) [2025-12-18 08:24:01 TP7] Scheduler hit an exception: Traceback (most recent call last):
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)   File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 2683, in run_scheduler_process
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)     scheduler.event_loop_normal()
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 120, in decorate_context
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)     return func(*args, **kwargs)
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)            ^^^^^^^^^^^^^^^^^^^^^
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)   File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 974, in event_loop_normal
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)     self.process_input_requests(recv_reqs)
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)   File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1187, in process_input_requests
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)     output = self._request_dispatcher(recv_req)
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)   File "/sgl-workspace/sglang/python/sglang/utils.py", line 507, in __call__
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)     return fn(obj)
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)            ^^^^^^^
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)   File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler_update_weights_mixin.py", line 88, in update_weights_from_tensor
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)     success, message = worker.update_weights_from_tensor(recv_req)
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)   File "/sgl-workspace/sglang/python/sglang/srt/speculative/eagle_worker.py", line 1029, in update_weights_from_tensor
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)     success, message = self.model_runner.update_weights_from_tensor(
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)   File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 1285, in update_weights_from_tensor
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)     return self._update_weights_from_flattened_bucket(
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)   File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 1336, in _update_weights_from_flattened_bucket
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)     self.model.load_weights(reconstructed_tensors)
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)   File "/sgl-workspace/sglang/python/sglang/srt/models/llama_eagle3.py", line 270, in load_weights
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)     weight_loader(param, loaded_weight)
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)   File "/sgl-workspace/sglang/python/sglang/srt/layers/vocab_parallel_embedding.py", line 452, in weight_loader
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)     assert loaded_weight.shape[output_dim] == (
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-12-18T16:24:02+08:00] leihaodi-qwen3-8b-rl-eagle3-20251218-162008s-3da56-cfcd2 >> (SGLangEngine pid=3111) AssertionError: self.org_vocab_size=32000 self.use_presharded_weights=False loaded_weight.shape[output_dim]=151936
```

it seems the SGlangEngine not get the right vocab_size for draft model, but when i only use SGLang or SpecForge, the SGlangEngine can work well. And Surprisingly, simply changing the`--sglang-speculative-algorithm` parameter from EAGLE3 to EAGLE restored normal program operation, yet the decode phase consistently displayed an acc length of 1—a critical flaw for speculative decoding. This suggests the draft model weights were never properly loaded when using EAGLE as the parameter.

This appears to be a Slime bug. Have you ever encountered this error? And what was the latest version of slime you were using at the time? Could it be version 0.2.0 earlier?

**Comment by JamesSand** [comment]
Hi I have encounter a similar error on this when I trained llama3 models. Is there any solutions?

cudaError error: 2 (out of memory)  file=csrc/core.cpp func=resume line=182

**Comment by guapisolo** [comment]
> Hi I have encounter a similar error on this when I trained llama3 models. Is there any solutions?
> 
> cudaError error: 2 (out of memory) file=csrc/core.cpp func=resume line=182

Hi @JamesSand , could you provide more details about your problem? Thanks!

**Comment by JamesSand** [comment]
> > Hi I have encounter a similar error on this when I trained llama3 models. Is there any solutions?
> > cudaError error: 2 (out of memory) file=csrc/core.cpp func=resume line=182
> 
> Hi [@JamesSand](https://github.com/JamesSand) , could you provide more details about your problem? Thanks!

Hi @guapisolo 

Thank you for your help. 

My issue is due to large `max_tokens_per_gpu` settings. I have fixed my issue by reducing that args. 

Thank you very much for your help!
