### ISSUE TITLE
Training hangs indefinitely after rollout phase completes on 8 B200 GPUs with CP=4, TP=2

### ISSUE THREAD

**Issue by euclidgame** [THUDM/slime#1487]
## Description
Training gets stuck indefinitely after the rollout phase completes and the training phase starts. The system shows only SGLang health check pings for hours with no training progress.

## Environment
Hardware: 8× NVIDIA B200 GPUs
Container: Slime official container
Model: Qwen3-4B

## Configuration
```
# Parallelism settings
--tensor-model-parallel-size 2
--sequence-parallel
--pipeline-model-parallel-size 1
--context-parallel-size 4
--expert-model-parallel-size 1
--expert-tensor-parallel-size 1

# Rollout settings
--rollout-batch-size 16
--n-samples-per-prompt 64
--rollout-max-response-len 40000
--num-steps-per-rollout 1

# Training settings
--colocate
--use-dynamic-batch-size
--max-tokens-per-gpu 32768
--calculate-per-token-loss
--use-slime-router

# SGLang settings
--rollout-num-gpus-per-engine 1
--sglang-mem-fraction-static 0.7
```

## Expected Behavior
Training should proceed after rollout phase completes, showing training metrics and gradient updates.

## Actual Behavior
The rollout phase completes successfully with metrics logged:
```
[2026-01-23 17:02:54] rollout 16: {'rollout/response_lengths': 18408.32, 'rollout/rewards': -8.03e-09, ...}
[2026-01-23 17:02:54] passrate 16: {'passrate/pass@1': 0.243, 'passrate/pass@2': 0.324, ...}
[2026-01-23 17:02:54] Timer actor_train start
```

After `actor_train` start, training hangs indefinitely. Only SGLang health check pings appear in the logs:
```
[2026-01-23 17:03:10] INFO: 172.17.0.2:43964 - "GET /health HTTP/1.1" 200 OK [repeated 8x across cluster]
[2026-01-23 17:03:40] INFO: 172.17.0.2:53212 - "GET /health HTTP/1.1" 200 OK [repeated 8x across cluster]
... (continues for hours with no training progress)
[2026-01-23 17:28:10] INFO: 172.17.0.2:42272 - "GET /health HTTP/1.1" 200 OK [repeated 8x across cluster]
```

The system remains in this state indefinitely with no training updates.

## Additional Notes
- The issue is intermittent - encountered multiple times with different training configurations, but not 100% reproducible
- Rollout phase always completes successfully; the hang occurs specifically at the training phase start
- The hang appears to be related to the `actor_train` step, possibly a deadlock in distributed training communication or weight synchronization
- Health checks indicate SGLang engines remain alive/healthy during the hang
- No OOM issues are observed

**Comment by lilei199908** [comment]
sry there not enough error msg that i can see. maybe you can observer what megatron actor doing when hanged by py-spy or ray dashboard

**Comment by leoleoasd** [comment]
We are observing similar behavior, turning `colocate` off helps

**Comment by BenjaminChoou** [comment]
I was also encountered with such an issue. It just hangs at `Timer actor_train start` and never continue.

GPUs: H100 80GB * 4

Related args are:
```
PERF_ARGS=(
   --tensor-model-parallel-size 2
   --sequence-parallel
   --pipeline-model-parallel-size 1
   --context-parallel-size 2
   --expert-model-parallel-size 1
   --expert-tensor-parallel-size 1
   --recompute-granularity full
   --recompute-method uniform
   --recompute-num-layers 1
   --use-dynamic-batch-size
   --max-tokens-per-gpu 9216
)

GRPO_ARGS=(
   --advantage-estimator grpo
   --use-kl-loss
   --kl-loss-coef 0.001
   --kl-loss-type low_var_kl
   --use-unbiased-kl
   --entropy-coef 0.001
   --eps-clip 0.2
   --eps-clip-high 0.28
)

OPTIMIZER_ARGS=(
   --optimizer adam
   --lr 1e-6
   --lr-decay-style constant
   --weight-decay 0.1
   --adam-beta1 0.9
   --adam-beta2 0.98
)

SGLANG_ARGS=(
   --rollout-num-gpus-per-engine 1
   --sglang-mem-fraction-static 0.7
   # If gemini API reports concurrency limit error, set this parameter to reduce the concurrency
   --sglang-server-concurrency 20
)

MISC_ARGS=(
   # default dropout in megatron is 0.1
   --attention-dropout 0.0
   --hidden-dropout 0.0
   # should be good for model performance
   --accumulate-allreduce-grads-in-fp32
   --attention-softmax-in-fp32
   # need to comment this when using model with MLA
   --attention-backend flash
)

CUSTOM_ARGS=(
   --custom-generate-function-path generate_with_tau.generate
)

python3 train.py \
--actor-num-nodes ${WORLD_SIZE} \
--actor-num-gpus-per-node ${GPU_NUM} \
--rollout-num-gpus ${GPU_NUM} \
# --colocate \
${MODEL_ARGS[@]} \
${CKPT_ARGS[@]} \
${ROLLOUT_ARGS[@]} \
${OPTIMIZER_ARGS[@]} \
${GRPO_ARGS[@]} \
${DISTRIBUTED_ARGS[@]} \
${WANDB_ARGS[@]} \
${PERF_ARGS[@]} \
${EVAL_ARGS[@]} \
${SGLANG_ARGS[@]} \
${MISC_ARGS[@]} \
${CUSTOM_ARGS[@]}

```


```
(MegatronTrainRayActor pid=19450) [2026-03-24 06:36:01] reloadable_process_group.py:165 - Reloading 14 process groups in pid 19450
(MegatronTrainRayActor pid=19450) [2026-03-24 06:36:01] memory_utils.py:41 - [Rank 0] Memory-Usage after wake_up model: {'gpu': '0', 'total_GB': 79.18, 'free_GB': 48.3, 'used_GB': 30.88, 'allocated_GB': 23.25, 'reserved_GB': 24.35}
(MegatronTrainRayActor pid=19450) [2026-03-24 06:36:01] timer.py:32 - Timer wake_up end (elapsed: 4.7s)
(MegatronTrainRayActor pid=19450) [2026-03-24 06:36:01] timer.py:24 - Timer data_preprocess start
(MegatronTrainRayActor pid=19450) [2026-03-24 06:36:02] timer.py:32 - Timer data_preprocess end (elapsed: 0.2s)
(SGLangEngine pid=17468) [2026-03-24 06:35:57] Cache flushed successfully! [repeated 7x across cluster]
(MegatronTrainRayActor pid=19450) [2026-03-24 06:36:02] timer.py:32 - Timer train_wait end (elapsed: 656.5s)
(MegatronTrainRayActor pid=19450) [2026-03-24 06:36:02] timer.py:24 - Timer train start
(MegatronTrainRayActor pid=19450) [2026-03-24 06:36:02] timer.py:24 - Timer ref_log_probs start
(MegatronTrainRayActor pid=19974) [2026-03-24 06:35:57] memory_utils.py:41 - [Rank 3] Memory-Usage before wake_up model: {'gpu': '3', 'total_GB': 79.18, 'free_GB': 73.57, 'used_GB': 5.61, 'allocated_GB': 23.24, 'reserved_GB': 25.17} [repeated 3x across cluster]
(SGLangEngine pid=17467) [2026-03-24 06:36:07] INFO:     172.17.0.11:52870 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
(SGLangEngine pid=17470) [2026-03-24 06:35:52] INFO:     172.17.0.11:51230 - "POST /abort_request HTTP/1.1" 200 OK [repeated 3x across cluster]
(SGLangEngine pid=17468) [2026-03-24 06:35:53] INFO:     172.17.0.11:59224 - "POST /generate HTTP/1.1" 200 OK
(SGLangEngine pid=17468) [2026-03-24 06:35:57] INFO:     172.17.0.11:54064 - "GET /flush_cache HTTP/1.1" 200 OK [repeated 3x across cluster]
(SGLangEngine pid=17470) [2026-03-24 06:35:57] INFO:     172.17.0.11:51246 - "POST /release_memory_occupation HTTP/1.1" 200 OK [repeated 3x across cluster]
(SGLangEngine pid=17467) [2026-03-24 06:36:22] INFO:     172.17.0.11:55180 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
(MegatronTrainRayActor pid=19450) [2026-03-24 06:36:27] timer.py:32 - Timer ref_log_probs end (elapsed: 24.7s)
(MegatronTrainRayActor pid=19977) [2026-03-24 06:36:02] reloadable_process_group.py:165 - Reloading 14 process groups in pid 19977 [repeated 3x across cluster]
(MegatronTrainRayActor pid=19977) [2026-03-24 06:36:02] memory_utils.py:41 - [Rank 1] Memory-Usage after wake_up model: {'gpu': '1', 'total_GB': 79.18, 'free_GB': 48.72, 'used_GB': 30.46, 'allocated_GB': 23.25, 'reserved_GB': 25.01} [repeated 3x across cluster]
(MegatronTrainRayActor pid=19450) [2026-03-24 06:36:27] timer.py:24 - Timer log_probs start
(SGLangEngine pid=17467) [2026-03-24 06:36:37] INFO:     172.17.0.11:39402 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
(MegatronTrainRayActor pid=19450) [2026-03-24 06:36:50] timer.py:32 - Timer log_probs end (elapsed: 23.7s)
(MegatronTrainRayActor pid=19450) [2026-03-24 06:36:50] data.py:212 - rollout 9: {'rollout/response_lengths': 3698.67578125, 'rollout/rewards': 2.6775524020195007e-09, 'rollout/truncated': 0.0, 'rollout/raw_reward': 0.3125, 'rollout/total_lengths': 8039.73046875, 'rollout/ref_log_probs': -0.1808299794793129, 'rollout/log_probs': -0.33891212567687035, 'rollout/advantages': -1.1175870895385742e-08, 'rollout/returns': -1.1175870895385742e-08}
(MegatronTrainRayActor pid=19450) [2026-03-24 06:36:50] data.py:212 - multi_turn 9: {'multi_turn/raw_response_length/response_length_mean': 3698.67578125, 'multi_turn/raw_response_length/response_length_max': 10692.0, 'multi_turn/raw_response_length/response_length_min': 342.0, 'multi_turn/raw_response_length/response_length_clip_ratio': 0.96484375, 'multi_turn/wo_obs_response_length/response_length_mean': 1369.04296875, 'multi_turn/wo_obs_response_length/response_length_max': 5005.0, 'multi_turn/wo_obs_response_length/response_length_min': 209.0}
(MegatronTrainRayActor pid=19450) [2026-03-24 06:36:50] data.py:212 - passrate 9: {'passrate/pass@1': 0.3125, 'passrate/pass@2': 0.5033482142857143, 'passrate/pass@4': 0.7424107142857143, 'passrate/pass@8': 1.0}
(MegatronTrainRayActor pid=19450) [2026-03-24 06:36:50] timer.py:24 - Timer actor_train start
(SGLangEngine pid=17467) [2026-03-24 06:36:52] INFO:     172.17.0.11:41646 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
(SGLangEngine pid=17467) [2026-03-24 06:37:07] INFO:     172.17.0.11:57206 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
(SGLangEngine pid=17467) [2026-03-24 06:37:22] INFO:     172.17.0.11:46008 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
(SGLangEngine pid=17467) [2026-03-24 06:37:37] INFO:     172.17.0.11:40382 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
(SGLangEngine pid=17467) [2026-03-24 06:37:52] INFO:     172.17.0.11:49772 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
(SGLangEngine pid=17467) [2026-03-24 06:38:07] INFO:     172.17.0.11:56158 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
(SGLangEngine pid=17467) [2026-03-24 06:38:22] INFO:     172.17.0.11:48418 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
(SGLangEngine pid=17467) [2026-03-24 06:38:37] INFO:     172.17.0.11:49226 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
(SGLangEngine pid=17467) [2026-03-24 06:38:52] INFO:     172.17.0.11:37128 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
...
(SGLangEngine pid=17467) [2026-03-24 13:00:52] INFO:     172.17.0.11:38556 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
(SGLangEngine pid=17467) [2026-03-24 13:01:07] INFO:     172.17.0.11:35618 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
(SGLangEngine pid=17467) [2026-03-24 13:01:22] INFO:     172.17.0.11:43546 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
(SGLangEngine pid=17467) [2026-03-24 13:01:37] INFO:     172.17.0.11:43634 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
(SGLangEngine pid=17467) [2026-03-24 13:01:52] INFO:     172.17.0.11:46902 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
```

**Comment by kim0806** [comment]
> I was also encountered with such an issue. It just hangs at `Timer actor_train start` and never continue.
> 
> GPUs: H100 80GB * 4
> 
> Related args are:
> 
> ```
> PERF_ARGS=(
>    --tensor-model-parallel-size 2
>    --sequence-parallel
>    --pipeline-model-parallel-size 1
>    --context-parallel-size 2
>    --expert-model-parallel-size 1
>    --expert-tensor-parallel-size 1
>    --recompute-granularity full
>    --recompute-method uniform
>    --recompute-num-layers 1
>    --use-dynamic-batch-size
>    --max-tokens-per-gpu 9216
> )
> 
> GRPO_ARGS=(
>    --advantage-estimator grpo
>    --use-kl-loss
>    --kl-loss-coef 0.001
>    --kl-loss-type low_var_kl
>    --use-unbiased-kl
>    --entropy-coef 0.001
>    --eps-clip 0.2
>    --eps-clip-high 0.28
> )
> 
> OPTIMIZER_ARGS=(
>    --optimizer adam
>    --lr 1e-6
>    --lr-decay-style constant
>    --weight-decay 0.1
>    --adam-beta1 0.9
>    --adam-beta2 0.98
> )
> 
> SGLANG_ARGS=(
>    --rollout-num-gpus-per-engine 1
>    --sglang-mem-fraction-static 0.7
>    # If gemini API reports concurrency limit error, set this parameter to reduce the concurrency
>    --sglang-server-concurrency 20
> )
> 
> MISC_ARGS=(
>    # default dropout in megatron is 0.1
>    --attention-dropout 0.0
>    --hidden-dropout 0.0
>    # should be good for model performance
>    --accumulate-allreduce-grads-in-fp32
>    --attention-softmax-in-fp32
>    # need to comment this when using model with MLA
>    --attention-backend flash
> )
> 
> CUSTOM_ARGS=(
>    --custom-generate-function-path generate_with_tau.generate
> )
> 
> python3 train.py \
> --actor-num-nodes ${WORLD_SIZE} \
> --actor-num-gpus-per-node ${GPU_NUM} \
> --rollout-num-gpus ${GPU_NUM} \
> # --colocate \
> ${MODEL_ARGS[@]} \
> ${CKPT_ARGS[@]} \
> ${ROLLOUT_ARGS[@]} \
> ${OPTIMIZER_ARGS[@]} \
> ${GRPO_ARGS[@]} \
> ${DISTRIBUTED_ARGS[@]} \
> ${WANDB_ARGS[@]} \
> ${PERF_ARGS[@]} \
> ${EVAL_ARGS[@]} \
> ${SGLANG_ARGS[@]} \
> ${MISC_ARGS[@]} \
> ${CUSTOM_ARGS[@]}
> ```
> 
> ```
> (MegatronTrainRayActor pid=19450) [2026-03-24 06:36:01] reloadable_process_group.py:165 - Reloading 14 process groups in pid 19450
> (MegatronTrainRayActor pid=19450) [2026-03-24 06:36:01] memory_utils.py:41 - [Rank 0] Memory-Usage after wake_up model: {'gpu': '0', 'total_GB': 79.18, 'free_GB': 48.3, 'used_GB': 30.88, 'allocated_GB': 23.25, 'reserved_GB': 24.35}
> (MegatronTrainRayActor pid=19450) [2026-03-24 06:36:01] timer.py:32 - Timer wake_up end (elapsed: 4.7s)
> (MegatronTrainRayActor pid=19450) [2026-03-24 06:36:01] timer.py:24 - Timer data_preprocess start
> (MegatronTrainRayActor pid=19450) [2026-03-24 06:36:02] timer.py:32 - Timer data_preprocess end (elapsed: 0.2s)
> (SGLangEngine pid=17468) [2026-03-24 06:35:57] Cache flushed successfully! [repeated 7x across cluster]
> (MegatronTrainRayActor pid=19450) [2026-03-24 06:36:02] timer.py:32 - Timer train_wait end (elapsed: 656.5s)
> (MegatronTrainRayActor pid=19450) [2026-03-24 06:36:02] timer.py:24 - Timer train start
> (MegatronTrainRayActor pid=19450) [2026-03-24 06:36:02] timer.py:24 - Timer ref_log_probs start
> (MegatronTrainRayActor pid=19974) [2026-03-24 06:35:57] memory_utils.py:41 - [Rank 3] Memory-Usage before wake_up model: {'gpu': '3', 'total_GB': 79.18, 'free_GB': 73.57, 'used_GB': 5.61, 'allocated_GB': 23.24, 'reserved_GB': 25.17} [repeated 3x across cluster]
> (SGLangEngine pid=17467) [2026-03-24 06:36:07] INFO:     172.17.0.11:52870 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> (SGLangEngine pid=17470) [2026-03-24 06:35:52] INFO:     172.17.0.11:51230 - "POST /abort_request HTTP/1.1" 200 OK [repeated 3x across cluster]
> (SGLangEngine pid=17468) [2026-03-24 06:35:53] INFO:     172.17.0.11:59224 - "POST /generate HTTP/1.1" 200 OK
> (SGLangEngine pid=17468) [2026-03-24 06:35:57] INFO:     172.17.0.11:54064 - "GET /flush_cache HTTP/1.1" 200 OK [repeated 3x across cluster]
> (SGLangEngine pid=17470) [2026-03-24 06:35:57] INFO:     172.17.0.11:51246 - "POST /release_memory_occupation HTTP/1.1" 200 OK [repeated 3x across cluster]
> (SGLangEngine pid=17467) [2026-03-24 06:36:22] INFO:     172.17.0.11:55180 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> (MegatronTrainRayActor pid=19450) [2026-03-24 06:36:27] timer.py:32 - Timer ref_log_probs end (elapsed: 24.7s)
> (MegatronTrainRayActor pid=19977) [2026-03-24 06:36:02] reloadable_process_group.py:165 - Reloading 14 process groups in pid 19977 [repeated 3x across cluster]
> (MegatronTrainRayActor pid=19977) [2026-03-24 06:36:02] memory_utils.py:41 - [Rank 1] Memory-Usage after wake_up model: {'gpu': '1', 'total_GB': 79.18, 'free_GB': 48.72, 'used_GB': 30.46, 'allocated_GB': 23.25, 'reserved_GB': 25.01} [repeated 3x across cluster]
> (MegatronTrainRayActor pid=19450) [2026-03-24 06:36:27] timer.py:24 - Timer log_probs start
> (SGLangEngine pid=17467) [2026-03-24 06:36:37] INFO:     172.17.0.11:39402 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> (MegatronTrainRayActor pid=19450) [2026-03-24 06:36:50] timer.py:32 - Timer log_probs end (elapsed: 23.7s)
> (MegatronTrainRayActor pid=19450) [2026-03-24 06:36:50] data.py:212 - rollout 9: {'rollout/response_lengths': 3698.67578125, 'rollout/rewards': 2.6775524020195007e-09, 'rollout/truncated': 0.0, 'rollout/raw_reward': 0.3125, 'rollout/total_lengths': 8039.73046875, 'rollout/ref_log_probs': -0.1808299794793129, 'rollout/log_probs': -0.33891212567687035, 'rollout/advantages': -1.1175870895385742e-08, 'rollout/returns': -1.1175870895385742e-08}
> (MegatronTrainRayActor pid=19450) [2026-03-24 06:36:50] data.py:212 - multi_turn 9: {'multi_turn/raw_response_length/response_length_mean': 3698.67578125, 'multi_turn/raw_response_length/response_length_max': 10692.0, 'multi_turn/raw_response_length/response_length_min': 342.0, 'multi_turn/raw_response_length/response_length_clip_ratio': 0.96484375, 'multi_turn/wo_obs_response_length/response_length_mean': 1369.04296875, 'multi_turn/wo_obs_response_length/response_length_max': 5005.0, 'multi_turn/wo_obs_response_length/response_length_min': 209.0}
> (MegatronTrainRayActor pid=19450) [2026-03-24 06:36:50] data.py:212 - passrate 9: {'passrate/pass@1': 0.3125, 'passrate/pass@2': 0.5033482142857143, 'passrate/pass@4': 0.7424107142857143, 'passrate/pass@8': 1.0}
> (MegatronTrainRayActor pid=19450) [2026-03-24 06:36:50] timer.py:24 - Timer actor_train start
> (SGLangEngine pid=17467) [2026-03-24 06:36:52] INFO:     172.17.0.11:41646 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> (SGLangEngine pid=17467) [2026-03-24 06:37:07] INFO:     172.17.0.11:57206 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> (SGLangEngine pid=17467) [2026-03-24 06:37:22] INFO:     172.17.0.11:46008 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> (SGLangEngine pid=17467) [2026-03-24 06:37:37] INFO:     172.17.0.11:40382 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> (SGLangEngine pid=17467) [2026-03-24 06:37:52] INFO:     172.17.0.11:49772 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> (SGLangEngine pid=17467) [2026-03-24 06:38:07] INFO:     172.17.0.11:56158 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> (SGLangEngine pid=17467) [2026-03-24 06:38:22] INFO:     172.17.0.11:48418 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> (SGLangEngine pid=17467) [2026-03-24 06:38:37] INFO:     172.17.0.11:49226 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> (SGLangEngine pid=17467) [2026-03-24 06:38:52] INFO:     172.17.0.11:37128 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> ...
> (SGLangEngine pid=17467) [2026-03-24 13:00:52] INFO:     172.17.0.11:38556 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> (SGLangEngine pid=17467) [2026-03-24 13:01:07] INFO:     172.17.0.11:35618 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> (SGLangEngine pid=17467) [2026-03-24 13:01:22] INFO:     172.17.0.11:43546 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> (SGLangEngine pid=17467) [2026-03-24 13:01:37] INFO:     172.17.0.11:43634 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> (SGLangEngine pid=17467) [2026-03-24 13:01:52] INFO:     172.17.0.11:46902 - "GET /metrics HTTP/1.1" 200 OK [repeated 4x across cluster]
> ```

请问这个问题解决了吗

**Comment by Qi2yU** [comment]
我碰到了类似的问题，不同的点在于我是在rollout的过程中卡住，随后只剩下sglang health generate了，不知道有没有解决办法

**Comment by David553** [comment]
We hit this exact shape on Miles (a slime fork that shares slime's `reloadable_process_group` + `sleep()`/`wake_up()` colocate path): rollout finishes, `Timer actor_train start`, then only SGLang health checks. Five multi-node attempts, always the same; single node fine. Posting what it turned out to be, because the 2-minute check applies here even if the cause differs.

**What the ranks were actually doing** (py-spy on all 16 ranks during the "hang"; 2 nodes × 8 H20, Qwen3.6-35B-A3B, TP2/PP2/EP8):
- PP stage 0, 8/8 ranks: `triton/backends/nvidia/compiler.py:make_llir` ← `triton/runtime/autotuner.py` ← `fla/ops/gated_delta_rule/chunk.py` — JIT compiling and autotuning the GDN kernels.
- PP stage 1, 8/8 ranks: `recv_forward` → `_communicate_shapes` → `torch.cuda.synchronize` — waiting for stage 0.

Not a deadlock: the cold first `actor_train` took 639 s (the log-prob pass before it 394 s); once `~/.triton/cache` was warm the same passes took 60 s and 13 s. The cache lives inside the container, so every fresh node compiles from scratch — which is why "works on one node, hangs on multi-node" looks like a communication bug.

**A slime-specific piece that turns a slow first step into a watchdog kill.** Colocate rebuilds every process group in `wake_up()`. Before #2208 (shipped in v0.3.1) the rebuild was `new_group(ranks=..., backend="nccl")` — `timeout`, `pg_options` and `group_desc` dropped — so after the first offload cycle every group ran with the default 10-minute timeout no matter what `--distributed-timeout-minutes` says. Confirmed with a 2-process probe: `_get_backend(device).options._timeout` goes `2:00:00 → 0:10:00` across `destroy_process_groups()` / `reload_process_groups()` on the old code, and stays `2:00:00` after the fix. It also fits @leoleoasd's "turning colocate off helps": no offload cycle, no rebuild.

**How to tell which case you're in** (Qwen3-4B has no GDN layer, so `fla` may not be your kernel — but something else may be compiling):
```
py-spy dump --pid <a MegatronTrainRayActor pid>    # one rank per node / pipeline stage
```
- some ranks inside `triton/.../compiler` or `torch/_inductor`, the rest in `recv_forward` / `synchronize` → first-step compile. Warm the Triton cache before the multi-node launch (or share `TRITON_CACHE_DIR` across nodes); on ≤ v0.3.0, raising `--distributed-timeout-minutes` only takes effect after upgrading.
- every rank inside a collective, none compiling → a real mismatch; please post the per-rank stacks plus the flight recorder dump (`TORCH_NCCL_DUMP_ON_TIMEOUT=1 TORCH_NCCL_TRACE_BUFFER_SIZE=2000`).

I'll open a small docs PR adding this check to `developer_guide/debug.md`.
