### ISSUE TITLE
[torch_memory_saver.cpp] CUresult error: 2 (out of memory)  file=csrc/utils.h func=cu_mem_create line=187

### ISSUE THREAD

**Issue by none0663** [THUDM/slime#274]
CUDA Out-of-Memory Error During Qwen30B-A3B Training
Environment:

Hardware: 2 machines, 16× H20 GPUs (96GB VRAM each)
Model: qwen30B-A3B
Code Commit: 9a291fca719e6c3fae1be93088b4fa79b774491a (HEAD -> main, origin/main, origin/HEAD)
Date:   Tue Sep 2 17:54:39 2025 +0800

Error Context: Training via ray.get(actor_model.async_train(...))
Error Log:`[torch_memory_saver.cpp] CUresult error: 2 (out of memory) file=csrc/utils.h func=cu_mem_create line=187`

Description:
When training the qwen30B-A3B model with various parallelism configurations (ep, pp, tp, cp), the CUDA OOM error consistently occurs during the async_train call. The error points to memory allocation failure in torch_memory_saver.cpp, despite using high-memory GPUs (H20 96GB).

 Is this a sglang-specific issue (e.g., memory fragmentation, Ray actor overhead) or inherent to the model’s memory demands when `actor_model.async_train`?

<img width="1881" height="931" alt="Image" src="https://github.com/user-attachments/assets/43eb174a-9396-422f-af8b-3e9ca46bea5d" />

**Comment by zhenghaoxu-gatech** [comment]
I met the same error when running `examples/retool_qwen3_4b_rl.sh` on 8*H100.

**Comment by none0663** [comment]
> I met the same error when running `examples/retool_qwen3_4b_rl.sh` on 8*H100.

You could try decreasing --sglang-mem-fraction-static to 0.5. Setting it to 0.5 worked for me.

**Comment by lucifer78901** [comment]
I also faced the bug. When I increase` --rollout-batch-size `and` --n-samples-per-prompt`，it works. Why？

**Comment by FortPercent** [comment]
I met the same error when running run-qwen3-30B-A3B.sh on 32*H100.

**Comment by DaizeDong** [comment]
Same error running `run-qwen3-30B-A3B.sh` with TP=4 and EP=8 on 8*H100. A strange thing is that this only occurs when saving the checkpoints. IDK if there are any bugs in the code.

**Comment by ypwang61** [comment]
meet the same problem...
